create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 14),
  name_key text generated always as (lower(trim(name))) stored unique,
  score integer not null default 0 check (score >= 0),
  updated_at timestamptz not null default now()
);

alter table public.leaderboard enable row level security;

drop policy if exists "Anyone can read leaderboard" on public.leaderboard;
create policy "Anyone can read leaderboard"
  on public.leaderboard for select
  to anon, authenticated
  using (true);

create or replace function public.submit_score(p_name text, p_score integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.leaderboard (name, score, updated_at)
  values (trim(p_name), greatest(p_score, 0), now())
  on conflict (name_key) do update
    set score = greatest(public.leaderboard.score, excluded.score),
        name = excluded.name,
        updated_at = case
          when excluded.score > public.leaderboard.score then now()
          else public.leaderboard.updated_at
        end;
end;
$$;

grant execute on function public.submit_score(text, integer) to anon, authenticated;

drop policy if exists "Score writes use submit_score" on public.leaderboard;
